#!/usr/bin/env node
/**
 * Generate secrets + HS256 API keys for the self-hosted Supabase stack and
 * write a ready-to-use .env (with sensible LOCAL-TEST defaults).
 *
 * Usage:
 *   node supabase/docker/generate-keys.mjs           # writes supabase/docker/.env
 *   node supabase/docker/generate-keys.mjs --print   # print secrets to stdout only
 *
 * Re-running refuses to overwrite an existing .env — regenerating JWT_SECRET
 * invalidates every issued session and breaks the anon/service keys baked into
 * the app build. To rotate intentionally: delete .env, then re-run.
 *
 * The anon/service keys are HS256 JWTs signed with JWT_SECRET — exactly the
 * shape Supabase uses. They go into the app as NEXT_PUBLIC_SUPABASE_ANON_KEY
 * and SUPABASE_SERVICE_ROLE_KEY.
 */
import { createHmac, randomBytes } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const b64url = (input) =>
  Buffer.from(input)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

function signJwt(payload, secret) {
  const segments = [b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' })), b64url(JSON.stringify(payload))];
  const signature = b64url(createHmac('sha256', secret).update(segments.join('.')).digest());
  return `${segments.join('.')}.${signature}`;
}

const iat = Math.floor(Date.now() / 1000);
const exp = iat + 60 * 60 * 24 * 365 * 10; // 10 years

// `--prod` targets the VM (public subdomain); default targets local testing.
const PROD = process.argv.includes('--prod');
const PUBLIC_URL = PROD ? 'https://supabase.playavalon.fun' : 'http://localhost:54321';
const SITE = PROD ? 'https://playavalon.fun' : 'http://localhost:3000';

const JWT_SECRET = randomBytes(32).toString('hex'); // 64 hex chars (>= 32 required)
const POSTGRES_PASSWORD = randomBytes(24).toString('hex'); // hex → safe in connection strings
const SECRET_KEY_BASE = randomBytes(48).toString('hex');
const DASHBOARD_PASSWORD = randomBytes(12).toString('hex');
const PG_META_CRYPTO_KEY = randomBytes(16).toString('hex');

const ANON_KEY = signJwt({ role: 'anon', iss: 'supabase', iat, exp }, JWT_SECRET);
const SERVICE_ROLE_KEY = signJwt({ role: 'service_role', iss: 'supabase', iat, exp }, JWT_SECRET);

if (process.argv.includes('--print')) {
  console.log(JSON.stringify({ JWT_SECRET, POSTGRES_PASSWORD, SECRET_KEY_BASE, ANON_KEY, SERVICE_ROLE_KEY }, null, 2));
  process.exit(0);
}

const envPath = join(dirname(fileURLToPath(import.meta.url)), '.env');
if (existsSync(envPath)) {
  console.error(`Refusing to overwrite existing ${envPath}.`);
  console.error('Delete it first to intentionally rotate secrets (this invalidates all sessions + baked app keys).');
  process.exit(1);
}

const env = `# GENERATED by generate-keys.mjs — secrets, DO NOT COMMIT (gitignored).
# Self-hosted Supabase config for playavalon. Defaults target LOCAL TESTING.
# For the VM deploy, change the URL block to https://supabase.playavalon.fun.

############ Secrets ############
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
SECRET_KEY_BASE=${SECRET_KEY_BASE}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}

############ Database ############
POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

############ API / URLs (${PROD ? 'PROD' : 'LOCAL TEST'}) ############
# Host ports 8000/5432 are commonly taken; use 54321/54322 (Supabase defaults).
KONG_HTTP_PORT=54321
API_EXTERNAL_URL=${PUBLIC_URL}
SUPABASE_PUBLIC_URL=${PUBLIC_URL}
SITE_URL=${SITE}
ADDITIONAL_REDIRECT_URLS=

############ Auth ############
JWT_EXPIRY=3600
DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false
SMTP_ADMIN_EMAIL=admin@playavalon.fun
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake
SMTP_PASS=fake
SMTP_SENDER_NAME=playavalon

############ PostgREST ############
PGRST_DB_SCHEMAS=public,graphql_public
PGRST_DB_MAX_ROWS=1000
PGRST_DB_EXTRA_SEARCH_PATH=public
`;

writeFileSync(envPath, env, { mode: 0o600 });
console.log(`Wrote ${envPath}`);
console.log(`\n--- App-side values for ${PROD ? "the app's .env on the VM" : 'local testing (.env.local)'} ---`);
console.log(`NEXT_PUBLIC_SUPABASE_URL=${PUBLIC_URL}`);
console.log(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}`);
console.log(`SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}`);
